version: '3.8'
services:
    nginx:
        image: nginx:latest
        ports:
            - "18080:8080"
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - laravel

    laravel:
        build: .
        ports:
            - "19000:9000"
        environment:
            TZ: "Asia/Tokyo"
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0.31
        ports:
            - "13306:3306"
        environment:
            TZ: "Asia/Tokyo"
            MYSQL_RANDOM_ROOT_PASSWORD: yes
            MYSQL_DATABASE: laravel_practice
            MYSQL_USER: app
            MYSQL_PASSWORD: app_user
        volumes:
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
